# TraceGuard AI – Synthetic Data Generation

## Objective

This notebook generates a fully synthetic automotive engineering dataset for the TraceGuard AI project.

The dataset simulates engineering lifecycle artifacts commonly found in ALM and Configuration Management environments, including:

- Requirements
- Specifications
- Test Cases
- Test Suites
- Engineering Inputs
- Change Requests
- Problem Reports
- Tasks
- Releases
- Traceability relationships
- Baseline history

The generated dataset is designed to support the development and evaluation of a Retrieval-Augmented Generation (RAG) system for engineering change impact analysis.

All data generated in this notebook is entirely synthetic and created for educational and portfolio purposes. No proprietary, confidential, employer-specific, or production engineering data is used.

In [2]:
# Import pandas for creating, manipulating, and saving tabular datasets
import pandas as pd

# Import NumPy for numerical operations and controlled random data generation
import numpy as np

# Import Python's random module for randomly selecting synthetic data values
import random

# Import defaultdict to easily organize and count different engineering artifact types
from collections import defaultdict

# Import Path to safely work with file and folder paths when saving our generated datasets
from pathlib import Path

In [22]:
# Create a NumPy random generator with a fixed seed so the dataset can be reproduced consistently
rng = np.random.default_rng(42)

# Set a fixed seed for Python's random module for reproducible random selections
random.seed(42)

# Define the total number of synthetic engineering artifacts we want to generate
TOTAL_RECORDS = 5000

# Define how many records of each engineering artifact type will be generated
artifact_distribution = {
    "ALM Test Case": 1984,
    "Change Request": 764,
    "ALM Specification": 733,
    "Task": 652,
    "Problem Report": 483,
    "ALM Requirement": 314,
    "Release": 50,
    "ALM Input": 18,
    "ALM Test Suite": 2,
}

# Verify that the sum of all artifact counts is exactly equal to our target of 5,000 records
assert sum(artifact_distribution.values()) == TOTAL_RECORDS

# Display the artifact distribution so we can verify it in the notebook
artifact_distribution

{'ALM Test Case': 1984,
 'Change Request': 764,
 'ALM Specification': 733,
 'Task': 652,
 'Problem Report': 483,
 'ALM Requirement': 314,
 'Release': 50,
 'ALM Input': 18,
 'ALM Test Suite': 2}

In [23]:
# Define fictional automotive engineering domains and the technical features within each domain
engineering_domains = {
    
    # Braking-related engineering features
    "Braking": [
        ("wheel speed", "wheel-speed signal plausibility and filtering"),
        ("wheel slip", "wheel-slip detection on low-friction surfaces"),
        ("brake pressure", "brake-pressure modulation and monitoring"),
        ("ABS control", "anti-lock braking intervention logic"),
        ("deceleration", "vehicle deceleration estimation"),
    ],

    # Battery-related engineering features
    "Battery": [
        ("cell voltage", "cell-voltage monitoring and plausibility"),
        ("battery temperature", "battery thermal protection"),
        ("state of charge", "state-of-charge estimation"),
        ("isolation", "high-voltage isolation monitoring"),
        ("charge current", "charging-current limitation"),
    ],

    # Steering-related engineering features
    "Steering": [
        ("steering angle", "steering-angle sensing and plausibility"),
        ("torque sensing", "driver torque sensing"),
        ("steering assist", "electric steering assist control"),
        ("fallback", "degraded steering fallback behavior"),
    ],

    # Powertrain-related engineering features
    "Powertrain": [
        ("motor torque", "traction motor torque control"),
        ("thermal derating", "powertrain thermal derating"),
        ("speed control", "motor-speed regulation"),
        ("torque limitation", "torque limitation during faults"),
    ],

    # Advanced Driver Assistance Systems (ADAS)-related engineering features
    "ADAS": [
        ("object detection", "object-detection confidence handling"),
        ("sensor fusion", "multi-sensor fusion plausibility"),
        ("distance estimation", "longitudinal distance estimation"),
        ("warning logic", "driver warning and escalation logic"),
    ],
}

# Convert the domain names into a list for easy random selection during synthetic data generation
domain_names = list(engineering_domains.keys())

# Display the available engineering domains
domain_names

['Braking', 'Battery', 'Steering', 'Powertrain', 'ADAS']

In [24]:
# Define a short ID prefix for each engineering artifact type
id_prefixes = {
    "ALM Test Case": "TC",
    "Change Request": "CR",
    "ALM Specification": "SPEC",
    "Task": "TASK",
    "Problem Report": "PR",
    "ALM Requirement": "REQ",
    "Release": "REL",
    "ALM Input": "INP",
    "ALM Test Suite": "TS",
}

# Create a dictionary that automatically starts the ID counter at zero for every artifact type
id_counters = defaultdict(int)

# Define a function that generates a new unique ID based on the artifact type
def generate_id(artifact_type):

    # Increase the counter for the requested artifact type by one
    id_counters[artifact_type] += 1

    # Get the correct prefix for the requested artifact type
    prefix = id_prefixes[artifact_type]

    # Return an ID with a five-digit sequential number, for example REQ-00001
    return f"{prefix}-{id_counters[artifact_type]:05d}"

# Generate sample IDs to verify that the ID generator works correctly
print(generate_id("ALM Requirement"))
print(generate_id("ALM Requirement"))
print(generate_id("Change Request"))
print(generate_id("ALM Test Case"))

REQ-00001
REQ-00002
CR-00001
TC-00001

In [25]:
# Reset all ID counters because the previous step generated sample IDs only for testing
id_counters = defaultdict(int)

# Create an empty list that will store each generated engineering artifact as a record
artifact_records = []

# Create a dictionary of lists to keep track of generated IDs for each artifact type
ids_by_type = defaultdict(list)

# Create an empty dictionary to remember the engineering domain and topic assigned to each generated artifact
theme_by_id = {}

# Define the fictional project and variant name that will be used for all records in this synthetic dataset
project_name = "Project NOVA / Variant EV-X"

# Print the project name to confirm that the dataset configuration is ready
print("Project:", project_name)

# Print the current number of generated records, which should be zero before data generation starts
print("Current artifact records:", len(artifact_records))

# Print a confirmation message showing that the data-generation structures are ready
print("Synthetic data generation setup is ready.")

Project: Project NOVA / Variant EV-X
Current artifact records: 0
Synthetic data generation setup is ready.

In [26]:
# Loop 50 times because our artifact distribution defines 50 synthetic Release records
for i in range(artifact_distribution["Release"]):

    # Generate a new unique Release ID, such as REL-00001
    release_id = generate_id("Release")

    # Store the generated Release ID so we can use it later when creating Covers relationships
    ids_by_type["Release"].append(release_id)

    # Create a synthetic release name using major and minor release numbers
    release_summary = f"Integrated automotive controls release {1 + i // 10}.{i % 10}"

    # Randomly select a lifecycle state for the synthetic Release
    release_state = random.choice(["Released", "Completed", "Active"])

    # Create the complete synthetic Release record and add it to our artifact records list
    artifact_records.append({
        "ID": release_id,
        "Document_ID": "",
        "Type": "Release",
        "Summary": release_summary,
        "Text": "",
        "State": release_state,
        "Project": project_name,
        "Spawns": "",
        "Covers": "",
    })

    # Store a generic engineering theme for the Release so every generated artifact has theme metadata
    theme_by_id[release_id] = ("Platform", "Release")

# Print the total number of Release records generated
print("Release records generated:", len(ids_by_type["Release"]))

# Print the total number of records currently stored in our dataset
print("Total artifact records:", len(artifact_records))

# Display the first three generated Release records so we can verify the output
pd.DataFrame(artifact_records).head(3)

Release records generated: 50
Total artifact records: 50

,ID,Document_ID,Type,Summary,Text,State,Project,Spawns,Covers
0,REL-00001,,Release,Integrated automotive controls release 1.0,,Active,Project NOVA / Variant EV-X,,
1,REL-00002,,Release,Integrated automotive controls release 1.1,,Released,Project NOVA / Variant EV-X,,
2,REL-00003,,Release,Integrated automotive controls release 1.2,,Released,Project NOVA / Variant EV-X,,

In [27]:
# Define the ALM artifact types that contain engineering text and can belong to engineering documents
alm_artifact_types = [
    "ALM Input",
    "ALM Requirement",
    "ALM Specification",
    "ALM Test Suite",
    "ALM Test Case",
]

# Define a document ID prefix for each ALM artifact type
document_prefixes = {
    "ALM Input": "DOC-INP",
    "ALM Requirement": "DOC-REQ",
    "ALM Specification": "DOC-SPEC",
    "ALM Test Suite": "DOC-TS",
    "ALM Test Case": "DOC-TC",
}

# Define multiple synthetic text templates for ALM Input artifacts
input_templates = [
    "Stakeholder input requires the {domain} function to support {detail} during nominal and degraded operating conditions.",
    "The vehicle program expects robust {detail} with appropriate diagnostic feedback available to dependent functions.",
    "The {domain} function is expected to maintain reliable {detail} across normal, boundary, and fault operating conditions.",
]

# Define multiple synthetic text templates for ALM Requirement artifacts
requirement_templates = [
    "The {domain} control system shall monitor {topic} and detect invalid or implausible conditions within the configured diagnostic interval.",
    "The system shall maintain {detail} when operating conditions cross calibrated boundary thresholds.",
    "The {domain} function shall transition to a defined safe behavior when {topic} is unavailable or implausible.",
    "The system shall provide diagnostic status information when a fault affecting {topic} is detected.",
    "The {domain} function shall recover normal operation after valid {topic} information becomes available again.",
]

# Define multiple synthetic text templates for ALM Specification artifacts
specification_templates = [
    "The {domain} software component shall implement {detail} using configurable thresholds, plausibility checks, and a defined fallback strategy.",
    "The processing logic for {topic} shall debounce transient faults and expose a diagnostic status to downstream consumers.",
    "The component shall calculate and validate {topic} before the value is used by dependent control functions.",
    "The software shall apply configurable monitoring thresholds to {topic} and trigger fallback behavior when the validation criteria are not satisfied.",
    "The {domain} component shall restore normal processing after {topic} remains valid for the configured recovery duration.",
]

# Define multiple synthetic text templates for ALM Test Case artifacts
test_case_templates = [
    "Verify {detail} by applying nominal, boundary, and fault-injection conditions and checking the expected system response.",
    "Validate the {domain} behavior for {topic} with transient signal disturbances and confirm diagnostic recovery.",
    "Execute boundary-value testing for {topic} and verify that fallback behavior and diagnostic reporting meet the expected criteria.",
    "Inject an invalid {topic} condition and verify that the {domain} function enters the expected degraded operating state.",
    "Restore valid {topic} information after a simulated fault and verify that the {domain} function recovers according to the expected behavior.",
]

# Define synthetic text templates for ALM Test Suite artifacts
test_suite_templates = [
    "Synthetic verification suite covering integrated {domain} scenarios, including nominal, boundary, degraded, and recovery behavior.",
    "Verification suite containing functional and fault-injection scenarios for {detail}.",
]

# Map each ALM artifact type to its corresponding list of text templates
text_templates = {
    "ALM Input": input_templates,
    "ALM Requirement": requirement_templates,
    "ALM Specification": specification_templates,
    "ALM Test Case": test_case_templates,
    "ALM Test Suite": test_suite_templates,
}

# Print the number of templates available for each artifact type to verify the configuration
for artifact_type, templates in text_templates.items():
    print(artifact_type, ":", len(templates), "templates")

ALM Input : 3 templates
ALM Requirement : 5 templates
ALM Specification : 5 templates
ALM Test Case : 5 templates
ALM Test Suite : 2 templates

In [28]:
# Loop through each ALM artifact type that we want to generate
for artifact_type in alm_artifact_types:

    # Get the required number of records for the current artifact type
    number_of_records = artifact_distribution[artifact_type]

    # Generate the required number of synthetic records for this artifact type
    for i in range(number_of_records):

        # Generate a unique ID for the current artifact, such as REQ-00001 or TC-00001
        artifact_id = generate_id(artifact_type)

        # Store the generated ID under its artifact type for later relationship creation
        ids_by_type[artifact_type].append(artifact_id)

        # Randomly select an automotive engineering domain, such as Braking or Battery
        domain = random.choice(domain_names)

        # Randomly select a topic and detailed feature belonging to the selected engineering domain
        topic, detail = random.choice(engineering_domains[domain])

        # Randomly select one of the text templates defined for the current artifact type
        selected_template = random.choice(text_templates[artifact_type])

        # Fill the selected template with the chosen domain, topic, and engineering feature
        artifact_text = selected_template.format(
            domain=domain.lower(),
            topic=topic,
            detail=detail,
        )

        # Generate a synthetic parent document ID by grouping approximately 40 artifacts into one document
        document_id = f"{document_prefixes[artifact_type]}-{(i // 40) + 1:04d}"

        # Randomly select a lifecycle state for the current ALM artifact
        artifact_state = random.choice([
            "ALM_Active",
            "Accepted",
            "Specified",
        ])

        # Add the completed synthetic ALM artifact as a new record in our main dataset list
        artifact_records.append({
            "ID": artifact_id,
            "Document_ID": document_id,
            "Type": artifact_type,
            "Summary": "",
            "Text": artifact_text,
            "State": artifact_state,
            "Project": project_name,
            "Spawns": "",
            "Covers": "",
        })

        # Store the engineering domain and topic of this artifact for creating meaningful traceability later
        theme_by_id[artifact_id] = (domain, topic)

# Print the number of generated records for each ALM artifact type
for artifact_type in alm_artifact_types:
    print(
        artifact_type,
        ":",
        len(ids_by_type[artifact_type]),
        "records"
    )

# Print the total number of records generated so far, including the 50 Release records
print("Total artifact records generated so far:", len(artifact_records))

ALM Input : 18 records
ALM Requirement : 314 records
ALM Specification : 733 records
ALM Test Suite : 2 records
ALM Test Case : 1984 records
Total artifact records generated so far: 3101

In [29]:
# Create an empty list to store all generated Change Request and Problem Report IDs
change_ids = []

# Loop through the two change-related artifact types
for artifact_type in ["Change Request", "Problem Report"]:

    # Get the number of records that need to be generated for the current artifact type
    number_of_records = artifact_distribution[artifact_type]

    # Generate the required number of Change Requests or Problem Reports
    for i in range(number_of_records):

        # Generate a unique ID, such as CR-00001 or PR-00001
        artifact_id = generate_id(artifact_type)

        # Store the ID under its corresponding artifact type
        ids_by_type[artifact_type].append(artifact_id)

        # Store the ID in the combined change list for creating traceability relationships later
        change_ids.append(artifact_id)

        # Randomly select an automotive engineering domain
        domain = random.choice(domain_names)

        # Randomly select a topic and detailed feature belonging to the selected domain
        topic, detail = random.choice(engineering_domains[domain])

        # Check whether the current artifact is a Change Request
        if artifact_type == "Change Request":

            # Define multiple synthetic summary patterns for Change Requests
            change_request_summaries = [
                f"Improve {detail} to increase robustness during degraded operating conditions.",
                f"Update {domain.lower()} logic for {topic} following revised functional behavior.",
                f"Refine {topic} handling to improve fault detection and recovery behavior.",
                f"Enhance {detail} to support improved diagnostic monitoring.",
                f"Modify {domain.lower()} processing for {topic} to handle transient fault conditions.",
            ]

            # Randomly select one Change Request summary
            artifact_summary = random.choice(change_request_summaries)

        # Handle the current artifact as a Problem Report
        else:

            # Define multiple synthetic summary patterns for Problem Reports
            problem_report_summaries = [
                f"Intermittent issue observed in {detail} during boundary operating conditions.",
                f"Unexpected {domain.lower()} behavior detected when {topic} becomes temporarily implausible.",
                f"Diagnostic recovery for {topic} does not meet the expected behavior under transient faults.",
                f"Incorrect fallback behavior observed for {detail} during fault injection.",
                f"Unexpected diagnostic response detected in {domain.lower()} processing of {topic}.",
            ]

            # Randomly select one Problem Report summary
            artifact_summary = random.choice(problem_report_summaries)

        # Randomly select a lifecycle state for the Change Request or Problem Report
        artifact_state = random.choice([
            "Accepted",
            "Completed",
            "Scheduled",
            "Open",
        ])

        # Add the generated Change Request or Problem Report to the main artifact dataset
        artifact_records.append({
            "ID": artifact_id,
            "Document_ID": "",
            "Type": artifact_type,
            "Summary": artifact_summary,
            "Text": "",
            "State": artifact_state,
            "Project": project_name,
            "Spawns": "",
            "Covers": "",
        })

        # Store the engineering domain and topic for creating meaningful relationships later
        theme_by_id[artifact_id] = (domain, topic)

# Print the number of generated Change Requests
print("Change Requests generated:", len(ids_by_type["Change Request"]))

# Print the number of generated Problem Reports
print("Problem Reports generated:", len(ids_by_type["Problem Report"]))

# Print the total number of change-related artifacts
print("Total CR and PR records:", len(change_ids))

# Print the total number of artifact records generated so far
print("Total artifact records generated so far:", len(artifact_records))

Change Requests generated: 764
Problem Reports generated: 483
Total CR and PR records: 1247
Total artifact records generated so far: 4348

In [30]:
# Get the total number of Task records that need to be generated
number_of_tasks = artifact_distribution["Task"]

# Loop through the required number of synthetic Task records
for i in range(number_of_tasks):

    # Generate a unique Task ID, such as TASK-00001
    task_id = generate_id("Task")

    # Store the generated Task ID for later use when creating Covers relationships
    ids_by_type["Task"].append(task_id)

    # Randomly select an automotive engineering domain for the Task
    domain = random.choice(domain_names)

    # Randomly select a topic and detailed feature belonging to the selected domain
    topic, detail = random.choice(engineering_domains[domain])

    # Define multiple synthetic Task summary patterns
    task_summaries = [
        f"Implement and review the proposed update for {detail}.",
        f"Perform technical analysis of {topic} changes in the {domain.lower()} function.",
        f"Update engineering artifacts affected by changes to {detail}.",
        f"Review and verify the implementation related to {topic}.",
        f"Perform integration activities for the updated {domain.lower()} behavior related to {topic}.",
    ]

    # Randomly select one of the Task summary patterns
    task_summary = random.choice(task_summaries)

    # Randomly select a lifecycle state for the Task
    task_state = random.choice([
        "Open",
        "In Progress",
        "Completed",
    ])

    # Add the completed synthetic Task record to our main dataset
    artifact_records.append({
        "ID": task_id,
        "Document_ID": "",
        "Type": "Task",
        "Summary": task_summary,
        "Text": "",
        "State": task_state,
        "Project": project_name,
        "Spawns": "",
        "Covers": "",
    })

    # Store the engineering domain and topic assigned to this Task for possible relationship analysis later
    theme_by_id[task_id] = (domain, topic)

# Print the total number of generated Task records
print("Tasks generated:", len(ids_by_type["Task"]))

# Print the total number of records in our synthetic dataset
print("Total artifact records:", len(artifact_records))

# Verify that our dataset contains exactly the planned 5,000 records
assert len(artifact_records) == TOTAL_RECORDS

# Print a confirmation message if the 5,000-record validation succeeds
print("Success: Exactly 5,000 synthetic artifact records have been generated.")

Tasks generated: 652
Total artifact records: 5000
Success: Exactly 5,000 synthetic artifact records have been generated.

In [31]:
# Convert the list of 5,000 synthetic artifact records into a Pandas DataFrame
artifacts_df = pd.DataFrame(artifact_records)

# Print the number of rows and columns in the generated DataFrame
print("Dataset shape:", artifacts_df.shape)

# Print the total number of unique IDs to verify that every artifact has a unique identifier
print("Unique IDs:", artifacts_df["ID"].nunique())

# Print the number of records available for each engineering artifact type
print("\nArtifact type distribution:")
print(artifacts_df["Type"].value_counts())

# Display the first five records so we can visually inspect the generated dataset structure
artifacts_df.head()

Dataset shape: (5000, 9)
Unique IDs: 5000

Artifact type distribution:
Type
ALM Test Case        1984
Change Request        764
ALM Specification     733
Task                  652
Problem Report        483
ALM Requirement       314
Release                50
ALM Input              18
ALM Test Suite          2
Name: count, dtype: int64

,ID,Document_ID,Type,Summary,Text,State,Project,Spawns,Covers
0,REL-00001,,Release,Integrated automotive controls release 1.0,,Active,Project NOVA / Variant EV-X,,
1,REL-00002,,Release,Integrated automotive controls release 1.1,,Released,Project NOVA / Variant EV-X,,
2,REL-00003,,Release,Integrated automotive controls release 1.2,,Released,Project NOVA / Variant EV-X,,
3,REL-00004,,Release,Integrated automotive controls release 1.3,,Active,Project NOVA / Variant EV-X,,
4,REL-00005,,Release,Integrated automotive controls release 1.4,,Completed,Project NOVA / Variant EV-X,,

In [32]:
# Create a dictionary that groups CR and PR IDs by their engineering domain and topic
changes_by_theme = defaultdict(list)

# Create another dictionary that groups CR and PR IDs only by their engineering domain
changes_by_domain = defaultdict(list)

# Loop through every generated Change Request and Problem Report ID
for change_id in change_ids:

    # Retrieve the engineering domain and topic previously assigned to this CR or PR
    domain, topic = theme_by_id[change_id]

    # Store the CR or PR under its exact combination of engineering domain and topic
    changes_by_theme[(domain, topic)].append(change_id)

    # Also store the CR or PR under its broader engineering domain
    changes_by_domain[domain].append(change_id)

# Define the artifact types that can contain CR or PR references in their Spawns field
spawnable_types = [
    "ALM Input",
    "ALM Requirement",
    "ALM Specification",
    "ALM Test Case",
    "Task",
]

# Find the DataFrame row indexes belonging to artifact types that can have Spawns relationships
spawnable_indexes = artifacts_df[
    artifacts_df["Type"].isin(spawnable_types)
].index.tolist()

# Loop through every artifact that is eligible to have a Spawns relationship
for index in spawnable_indexes:

    # Give approximately 62% of eligible artifacts at least one Spawns relationship
    if rng.random() < 0.62:

        # Get the unique ID of the current artifact
        artifact_id = artifacts_df.at[index, "ID"]

        # Retrieve the engineering domain and topic assigned to the current artifact
        domain, topic = theme_by_id[artifact_id]

        # First try to find CRs or PRs that match both the exact domain and topic
        matching_changes = changes_by_theme[(domain, topic)]

        # If no exact theme match exists, use CRs or PRs from the same engineering domain
        if not matching_changes:
            matching_changes = changes_by_domain[domain]

        # Randomly choose whether this artifact should reference one, two, or three CRs or PRs
        number_of_links = int(rng.integers(1, 4))

        # Randomly select the required number of unique matching CR or PR IDs
        selected_changes = random.sample(
            matching_changes,
            min(number_of_links, len(matching_changes))
        )

        # Store the selected CR or PR IDs as a comma-separated value in the Spawns column
        artifacts_df.at[index, "Spawns"] = ", ".join(selected_changes)

# Count how many artifacts now contain at least one Spawns relationship
artifacts_with_spawns = (artifacts_df["Spawns"] != "").sum()

# Print the number of artifacts that received Spawns relationships
print("Artifacts with Spawns relationships:", artifacts_with_spawns)

# Display a sample of records containing Spawns relationships for manual verification
artifacts_df[
    artifacts_df["Spawns"] != ""
][["ID", "Type", "Summary", "Text", "Spawns"]].head(10)

Artifacts with Spawns relationships: 2346

,ID,Type,Summary,Text,Spawns
51,INP-00002,ALM Input,,The vehicle program expects robust traction mo...,"CR-00416, PR-00039"
53,INP-00004,ALM Input,,The steering function is expected to maintain ...,"CR-00097, PR-00450, CR-00326"
57,INP-00008,ALM Input,,The steering function is expected to maintain ...,"PR-00243, CR-00402, CR-00396"
58,INP-00009,ALM Input,,The braking function is expected to maintain r...,"CR-00019, PR-00308"
62,INP-00013,ALM Input,,Stakeholder input requires the braking functio...,"CR-00704, CR-00702"
63,INP-00014,ALM Input,,Stakeholder input requires the powertrain func...,CR-00091
64,INP-00015,ALM Input,,Stakeholder input requires the adas function t...,"PR-00365, PR-00398, CR-00138"
67,INP-00018,ALM Input,,The adas function is expected to maintain reli...,"CR-00371, CR-00674, CR-00065"
71,REQ-00004,ALM Requirement,,The battery function shall recover normal oper...,"PR-00247, PR-00426"
72,REQ-00005,ALM Requirement,,The powertrain function shall recover normal o...,"CR-00003, PR-00251"

In [33]:
# Create an empty set to store all CR and PR IDs currently referenced in the Spawns column
referenced_change_ids = set()

# Loop through every non-empty value in the Spawns column
for spawns_value in artifacts_df["Spawns"]:

    # Split comma-separated Spawns values into individual CR or PR IDs
    individual_ids = [
        item.strip()
        for item in str(spawns_value).split(",")
        if item.strip()
    ]

    # Add all extracted CR or PR IDs to the set of referenced change IDs
    referenced_change_ids.update(individual_ids)

# Loop through every generated Change Request and Problem Report ID
for change_id in change_ids:

    # Check whether the current CR or PR is missing from all existing Spawns relationships
    if change_id not in referenced_change_ids:

        # Retrieve the engineering domain and topic assigned to the unreferenced CR or PR
        domain, topic = theme_by_id[change_id]

        # Find eligible artifacts that belong to the exact same engineering domain and topic
        matching_indexes = [
            index
            for index in spawnable_indexes
            if theme_by_id[artifacts_df.at[index, "ID"]] == (domain, topic)
        ]

        # If exact theme matches are available, randomly select one eligible artifact
        if matching_indexes:
            selected_index = random.choice(matching_indexes)

            # Get the current Spawns value of the selected artifact
            existing_spawns = artifacts_df.at[selected_index, "Spawns"]

            # Add the missing CR or PR ID while preserving any existing Spawns relationships
            if existing_spawns:
                artifacts_df.at[selected_index, "Spawns"] = (
                    existing_spawns + ", " + change_id
                )
            else:
                artifacts_df.at[selected_index, "Spawns"] = change_id

# Create a set containing every valid artifact ID available in our complete dataset
all_artifact_ids = set(artifacts_df["ID"])

# Create an empty list that will hold every individual Spawns reference for validation
all_spawn_references = []

# Loop through every value stored in the Spawns column
for spawns_value in artifacts_df["Spawns"]:

    # Split each comma-separated Spawns value and add the individual IDs to our validation list
    all_spawn_references.extend([
        item.strip()
        for item in str(spawns_value).split(",")
        if item.strip()
    ])

# Count how many individual Spawns references exist in the dataset
total_spawn_references = len(all_spawn_references)

# Count how many Spawns references point to IDs that actually exist in the dataset
resolved_spawn_references = sum(
    reference in all_artifact_ids
    for reference in all_spawn_references
)

# Calculate the number of Spawns references that point to missing IDs
unresolved_spawn_references = (
    total_spawn_references - resolved_spawn_references
)

# Calculate the percentage of Spawns references that successfully resolve to existing artifacts
spawn_resolution_percentage = (
    resolved_spawn_references / total_spawn_references * 100
    if total_spawn_references > 0
    else 0
)

# Print the final Spawns traceability validation results
print("Total Spawns references:", total_spawn_references)
print("Resolved Spawns references:", resolved_spawn_references)
print("Unresolved Spawns references:", unresolved_spawn_references)
print(f"Spawns resolution percentage: {spawn_resolution_percentage:.2f}%")

# Print the number of unique CR and PR IDs that are referenced through Spawns
print(
    "Unique CR/PR IDs referenced:",
    len(set(all_spawn_references))
)

# Print the total number of generated CR and PR records for comparison
print(
    "Total CR/PR records:",
    len(change_ids)
)

Total Spawns references: 4752
Resolved Spawns references: 4752
Unresolved Spawns references: 0
Spawns resolution percentage: 100.00%
Unique CR/PR IDs referenced: 1247
Total CR/PR records: 1247

In [34]:
# Combine all Change Request, Problem Report, and Task IDs that can be covered by a Release
coverable_ids = (
    ids_by_type["Change Request"]
    + ids_by_type["Problem Report"]
    + ids_by_type["Task"]
)

# Shuffle the IDs so they are distributed randomly across the synthetic Releases
random.shuffle(coverable_ids)

# Split all coverable IDs into approximately equal groups, one group for each Release
release_cover_groups = np.array_split(
    coverable_ids,
    len(ids_by_type["Release"])
)

# Loop through each Release ID together with its assigned group of CR, PR, and Task IDs
for release_id, covered_items in zip(
    ids_by_type["Release"],
    release_cover_groups
):

    # Convert the NumPy array of covered item IDs into a normal Python list
    covered_items_list = list(covered_items)

    # Convert the list of IDs into a comma-separated string for the Covers column
    covers_value = ", ".join(covered_items_list)

    # Find the row belonging to the current Release and store its Covers relationships
    artifacts_df.loc[
        artifacts_df["ID"] == release_id,
        "Covers"
    ] = covers_value

# Create an empty list to collect every individual ID referenced in the Covers column
all_cover_references = []

# Loop through every value in the Covers column
for covers_value in artifacts_df["Covers"]:

    # Split comma-separated Covers values into individual artifact IDs
    individual_ids = [
        item.strip()
        for item in str(covers_value).split(",")
        if item.strip()
    ]

    # Add the extracted IDs to the complete Covers reference list
    all_cover_references.extend(individual_ids)

# Count the total number of individual Covers relationships in the dataset
total_cover_references = len(all_cover_references)

# Count how many Covers references point to IDs that actually exist in our dataset
resolved_cover_references = sum(
    reference in all_artifact_ids
    for reference in all_cover_references
)

# Calculate how many Covers references point to missing or invalid IDs
unresolved_cover_references = (
    total_cover_references - resolved_cover_references
)

# Calculate the percentage of Covers references that successfully resolve to existing artifacts
covers_resolution_percentage = (
    resolved_cover_references / total_cover_references * 100
    if total_cover_references > 0
    else 0
)

# Print the total number of generated Covers relationships
print("Total Covers references:", total_cover_references)

# Print the number of Covers references that successfully resolve to an existing artifact
print("Resolved Covers references:", resolved_cover_references)

# Print the number of Covers references that point to missing artifacts
print("Unresolved Covers references:", unresolved_cover_references)

# Print the Covers relationship resolution percentage
print(f"Covers resolution percentage: {covers_resolution_percentage:.2f}%")

# Print the number of unique CR, PR, and Task IDs referenced through Covers
print("Unique items covered:", len(set(all_cover_references)))

# Print the total number of CR, PR, and Task records available for comparison
print("Total coverable items:", len(coverable_ids))

Total Covers references: 1899
Resolved Covers references: 1899
Unresolved Covers references: 0
Covers resolution percentage: 100.00%
Unique items covered: 1899
Total coverable items: 1899

In [35]:
# Define generic engineering lifecycle milestones for creating baseline labels
lifecycle_milestones = [
    "CONCEPT",
    "DESIGN",
    "DEV",
    "INT",
    "VER",
    "VAL",
    "PROD",
]

# Define the ALM artifact types that are eligible to have baseline history
baseline_applicable_types = [
    "ALM Input",
    "ALM Requirement",
    "ALM Specification",
    "ALM Test Case",
    "ALM Test Suite",
]

# Create an empty list that will store all generated baseline history records
baseline_records = []

# Create an empty dictionary to map every CR or PR ID to the Release that covers it
change_to_release = {}

# Filter the main dataset to retrieve only Release records
release_records = artifacts_df[
    artifacts_df["Type"] == "Release"
]

# Loop through every Release record in the dataset
for _, release in release_records.iterrows():

    # Retrieve the unique ID of the current Release
    release_id = release["ID"]

    # Split the comma-separated Covers field into individual covered artifact IDs
    covered_ids = [
        item.strip()
        for item in str(release["Covers"]).split(",")
        if item.strip()
    ]

    # Loop through every artifact ID covered by the current Release
    for covered_id in covered_ids:

        # Check whether the covered artifact is a Change Request or Problem Report
        if (
            covered_id in ids_by_type["Change Request"]
            or covered_id in ids_by_type["Problem Report"]
        ):

            # Store the relationship between the CR/PR and its covering Release
            change_to_release[covered_id] = release_id

# Create synthetic chronological dates for the 50 Releases
release_dates = pd.date_range(
    start="2024-01-15",
    end="2026-06-30",
    periods=len(ids_by_type["Release"])
)

# Create a dictionary that maps every Release ID to its synthetic chronological date
release_date_map = dict(
    zip(
        ids_by_type["Release"],
        release_dates
    )
)

# Create a dictionary that maps every Release ID to a lifecycle milestone
release_milestone_map = {}

# Loop through every generated Release ID together with its position
for index, release_id in enumerate(ids_by_type["Release"]):

    # Assign lifecycle milestones cyclically across the generated Releases
    milestone = lifecycle_milestones[
        index % len(lifecycle_milestones)
    ]

    # Store the milestone assigned to the current Release
    release_milestone_map[release_id] = milestone

# Filter the main dataset to retrieve only ALM artifacts eligible for baseline history
baseline_applicable_artifacts = artifacts_df[
    artifacts_df["Type"].isin(baseline_applicable_types)
]

# Loop through every baseline-eligible ALM artifact
for _, artifact in baseline_applicable_artifacts.iterrows():

    # Retrieve the unique ID of the current ALM artifact
    artifact_id = artifact["ID"]

    # Split the artifact's comma-separated Spawns field into individual CR or PR IDs
    spawned_change_ids = [
        item.strip()
        for item in str(artifact["Spawns"]).split(",")
        if item.strip()
    ]

    # Create an empty set to store Releases associated with this artifact through CR/PR traceability
    associated_releases = set()

    # Loop through every CR or PR referenced by the current artifact
    for change_id in spawned_change_ids:

        # Check whether the CR or PR is mapped to a Release
        if change_id in change_to_release:

            # Add the corresponding Release ID to the artifact's associated Releases
            associated_releases.add(
                change_to_release[change_id]
            )

    # Sort the associated Releases using their synthetic chronological Release dates
    associated_releases = sorted(
        associated_releases,
        key=lambda release_id: release_date_map[release_id]
    )

    # Loop through every Release associated with the current ALM artifact
    for release_id in associated_releases:

        # Retrieve the lifecycle milestone assigned to the associated Release
        milestone = release_milestone_map[release_id]

        # Create a baseline label using the project name, milestone, and Release ID
        baseline_label = (
            f"BL-NOVA-{milestone}-{release_id}"
        )

        # Retrieve the synthetic baseline date associated with the Release
        baseline_date = release_date_map[
            release_id
        ].date()

        # Add the complete baseline history record to our baseline dataset
        baseline_records.append({
            "Artifact_ID": artifact_id,
            "Document_ID": artifact["Document_ID"],
            "Type": artifact["Type"],
            "Baseline_Label": baseline_label,
            "Baseline_Date": baseline_date,
            "Release_ID": release_id,
            "Milestone": milestone,
        })

# Convert all generated baseline history records into a Pandas DataFrame
baselines_df = pd.DataFrame(
    baseline_records
)

# Print the total number of baseline history records generated
print(
    "Total baseline history records:",
    len(baselines_df)
)

# Print the number of unique ALM artifacts that have at least one baseline
print(
    "Artifacts with baseline history:",
    baselines_df["Artifact_ID"].nunique()
)

# Print the number of unique Releases represented in the baseline history
print(
    "Releases represented in baselines:",
    baselines_df["Release_ID"].nunique()
)

# Display the first ten generated baseline history records for manual verification
baselines_df.head(10)

Total baseline history records: 3871
Artifacts with baseline history: 1939
Releases represented in baselines: 50

,Artifact_ID,Document_ID,Type,Baseline_Label,Baseline_Date,Release_ID,Milestone
0,INP-00002,DOC-INP-0001,ALM Input,BL-NOVA-CONCEPT-REL-00001,2024-01-15,REL-00001,CONCEPT
1,INP-00002,DOC-INP-0001,ALM Input,BL-NOVA-INT-REL-00046,2026-04-17,REL-00046,INT
2,INP-00004,DOC-INP-0001,ALM Input,BL-NOVA-DEV-REL-00017,2024-11-02,REL-00017,DEV
3,INP-00004,DOC-INP-0001,ALM Input,BL-NOVA-DEV-REL-00031,2025-07-17,REL-00031,DEV
4,INP-00004,DOC-INP-0001,ALM Input,BL-NOVA-CONCEPT-REL-00036,2025-10-16,REL-00036,CONCEPT
5,INP-00008,DOC-INP-0001,ALM Input,BL-NOVA-VER-REL-00012,2024-08-03,REL-00012,VER
6,INP-00008,DOC-INP-0001,ALM Input,BL-NOVA-INT-REL-00018,2024-11-21,REL-00018,INT
7,INP-00008,DOC-INP-0001,ALM Input,BL-NOVA-CONCEPT-REL-00050,2026-06-30,REL-00050,CONCEPT
8,INP-00009,DOC-INP-0001,ALM Input,BL-NOVA-DESIGN-REL-00037,2025-11-04,REL-00037,DESIGN
9,INP-00009,DOC-INP-0001,ALM Input,BL-NOVA-DEV-REL-00038,2025-11-22,REL-00038,DEV

In [37]:
# Create an empty list to store the synthetic evaluation Change Requests
evaluation_records = []

# Create a list of ALM artifact types that should be considered for impact retrieval evaluation
evaluation_target_types = [
    "ALM Input",
    "ALM Requirement",
    "ALM Specification",
    "ALM Test Case",
]

# Filter the main dataset to retrieve only ALM artifacts that can be considered relevant retrieval targets
evaluation_target_artifacts = artifacts_df[
    artifacts_df["Type"].isin(evaluation_target_types)
]

# Define multiple summary templates for generating unseen evaluation Change Requests
evaluation_cr_templates = [
    "Improve {detail} to increase robustness under intermittent operating conditions.",
    "Update {domain} behavior related to {topic} following revised system requirements.",
    "Modify {topic} processing to improve diagnostic detection and recovery.",
    "Enhance {detail} to support degraded operating conditions and fault handling.",
    "Revise {domain} logic for {topic} to improve boundary-condition handling.",
    "Introduce updated monitoring behavior for {topic} within the {domain} function.",
]

# Generate 100 synthetic Change Requests that will be used only for retrieval evaluation
for i in range(100):

    # Randomly select an engineering domain for the unseen evaluation Change Request
    domain = random.choice(domain_names)

    # Randomly select a topic and detailed engineering feature from the selected domain
    topic, detail = random.choice(
        engineering_domains[domain]
    )

    # Randomly select one of the evaluation Change Request summary templates
    selected_template = random.choice(
        evaluation_cr_templates
    )

    # Generate the natural-language summary of the unseen evaluation Change Request
    evaluation_summary = selected_template.format(
        domain=domain.lower(),
        topic=topic,
        detail=detail,
    )

    # Create a unique evaluation Change Request ID that does not overlap with the main dataset IDs
    evaluation_cr_id = f"EVAL-CR-{i + 1:03d}"

    # Create an empty list to store the IDs of artifacts considered relevant to this evaluation CR
    relevant_artifact_ids = []

    # Loop through every eligible ALM artifact in the main knowledge-base dataset
    for _, artifact in evaluation_target_artifacts.iterrows():

        # Retrieve the engineering domain and topic previously assigned to the current artifact
        artifact_domain, artifact_topic = theme_by_id[
            artifact["ID"]
        ]

        # Treat artifacts with the exact same domain and topic as relevant ground-truth artifacts
        if (
            artifact_domain == domain
            and artifact_topic == topic
        ):

            # Add the matching artifact ID to the ground-truth relevant artifact list
            relevant_artifact_ids.append(
                artifact["ID"]
            )

    # Add the evaluation Change Request and its known ground-truth information to the evaluation dataset
    evaluation_records.append({
        "Evaluation_CR_ID": evaluation_cr_id,
        "Summary": evaluation_summary,
        "Domain": domain,
        "Topic": topic,
        "Ground_Truth_Artifact_IDs": ", ".join(
            relevant_artifact_ids
        ),
        "Ground_Truth_Count": len(
            relevant_artifact_ids
        ),
    })

# Convert the evaluation records into a separate Pandas DataFrame
evaluation_df = pd.DataFrame(
    evaluation_records
)

# Print the total number of evaluation Change Requests generated
print(
    "Evaluation CRs generated:",
    len(evaluation_df)
)

# Print the minimum number of relevant ground-truth artifacts assigned to any evaluation CR
print(
    "Minimum ground-truth artifacts:",
    evaluation_df["Ground_Truth_Count"].min()
)

# Print the maximum number of relevant ground-truth artifacts assigned to any evaluation CR
print(
    "Maximum ground-truth artifacts:",
    evaluation_df["Ground_Truth_Count"].max()
)

# Print the average number of relevant ground-truth artifacts across all evaluation CRs
print(
    "Average ground-truth artifacts:",
    round(
        evaluation_df["Ground_Truth_Count"].mean(),
        2
    )
)

# Display the first five evaluation Change Requests for manual verification
evaluation_df.head()

Evaluation CRs generated: 100
Minimum ground-truth artifacts: 111
Maximum ground-truth artifacts: 167
Average ground-truth artifacts: 139.83

,Evaluation_CR_ID,Summary,Domain,Topic,Ground_Truth_Artifact_IDs,Ground_Truth_Count
0,EVAL-CR-001,Update battery behavior related to state of ch...,Battery,state of charge,"INP-00017, REQ-00018, REQ-00020, REQ-00027, RE...",117
1,EVAL-CR-002,Enhance vehicle deceleration estimation to sup...,Braking,deceleration,"INP-00009, REQ-00007, REQ-00046, REQ-00051, RE...",126
2,EVAL-CR-003,Revise powertrain logic for torque limitation ...,Powertrain,torque limitation,"INP-00016, REQ-00001, REQ-00005, REQ-00151, RE...",165
3,EVAL-CR-004,Modify deceleration processing to improve diag...,Braking,deceleration,"INP-00009, REQ-00007, REQ-00046, REQ-00051, RE...",126
4,EVAL-CR-005,Update adas behavior related to warning logic ...,ADAS,warning logic,"REQ-00043, REQ-00082, REQ-00085, REQ-00111, RE...",161

In [38]:
# Print a heading for the main dataset validation results
print("=== MAIN DATASET VALIDATION ===")

# Check and print the total number of records in the main synthetic dataset
print("Total records:", len(artifacts_df))

# Check and print the total number of unique artifact IDs
print("Unique IDs:", artifacts_df["ID"].nunique())

# Count and print the number of duplicated artifact IDs
print("Duplicate IDs:", artifacts_df["ID"].duplicated().sum())

# Check whether the dataset contains exactly the planned number of records
print("Expected 5,000 records:", len(artifacts_df) == 5000)

# Print the distribution of records across all artifact types
print("\nArtifact type distribution:")
print(artifacts_df["Type"].value_counts())


# Print a heading for engineering content validation
print("\n=== CONTENT VALIDATION ===")

# Define artifact types that are expected to contain engineering content in the Text column
text_required_types = [
    "ALM Input",
    "ALM Requirement",
    "ALM Specification",
    "ALM Test Case",
    "ALM Test Suite",
]

# Define artifact types that are expected to contain content in the Summary column
summary_required_types = [
    "Change Request",
    "Problem Report",
    "Task",
    "Release",
]

# Count ALM artifacts where the Text field is unexpectedly empty
missing_text_count = artifacts_df[
    artifacts_df["Type"].isin(text_required_types)
]["Text"].eq("").sum()

# Count CR, PR, Task, and Release records where the Summary field is unexpectedly empty
missing_summary_count = artifacts_df[
    artifacts_df["Type"].isin(summary_required_types)
]["Summary"].eq("").sum()

# Print the number of ALM artifacts missing required Text content
print("ALM artifacts missing Text:", missing_text_count)

# Print the number of summary-based artifacts missing required Summary content
print("CR/PR/Task/Release missing Summary:", missing_summary_count)


# Print a heading for duplicate content validation
print("\n=== DUPLICATE CONTENT VALIDATION ===")

# Count the number of duplicated non-empty Text values in the synthetic dataset
duplicate_text_count = artifacts_df[
    artifacts_df["Text"] != ""
]["Text"].duplicated().sum()

# Count the number of duplicated non-empty Summary values in the synthetic dataset
duplicate_summary_count = artifacts_df[
    artifacts_df["Summary"] != ""
]["Summary"].duplicated().sum()

# Print the number of exact duplicate Text values
print("Duplicate non-empty Text values:", duplicate_text_count)

# Print the number of exact duplicate Summary values
print("Duplicate non-empty Summary values:", duplicate_summary_count)


# Print a heading for Spawns relationship validation
print("\n=== SPAWNS VALIDATION ===")

# Print the previously calculated total number of Spawns references
print("Total Spawns references:", total_spawn_references)

# Print the previously calculated number of resolved Spawns references
print("Resolved Spawns references:", resolved_spawn_references)

# Print the previously calculated number of unresolved Spawns references
print("Unresolved Spawns references:", unresolved_spawn_references)

# Print the percentage of Spawns references that successfully resolve to existing records
print(f"Spawns resolution: {spawn_resolution_percentage:.2f}%")


# Print a heading for Covers relationship validation
print("\n=== COVERS VALIDATION ===")

# Print the previously calculated total number of Covers references
print("Total Covers references:", total_cover_references)

# Print the previously calculated number of resolved Covers references
print("Resolved Covers references:", resolved_cover_references)

# Print the previously calculated number of unresolved Covers references
print("Unresolved Covers references:", unresolved_cover_references)

# Print the percentage of Covers references that successfully resolve to existing records
print(f"Covers resolution: {covers_resolution_percentage:.2f}%")


# Print a heading for baseline history validation
print("\n=== BASELINE VALIDATION ===")

# Count and print the total number of baseline history records
print("Total baseline records:", len(baselines_df))

# Count and print the number of unique artifacts represented in the baseline history
print(
    "Artifacts with baselines:",
    baselines_df["Artifact_ID"].nunique()
)

# Count and print the number of unique Releases represented in the baseline history
print(
    "Releases represented:",
    baselines_df["Release_ID"].nunique()
)

# Check whether every Artifact_ID referenced in the baseline dataset exists in the main artifact dataset
invalid_baseline_artifacts = (
    ~baselines_df["Artifact_ID"].isin(all_artifact_ids)
).sum()

# Check whether every Release_ID referenced in the baseline dataset exists in the generated Release ID list
invalid_baseline_releases = (
    ~baselines_df["Release_ID"].isin(
        ids_by_type["Release"]
    )
).sum()

# Print the number of baseline records referencing missing artifacts
print(
    "Invalid baseline Artifact_ID references:",
    invalid_baseline_artifacts
)

# Print the number of baseline records referencing missing Releases
print(
    "Invalid baseline Release_ID references:",
    invalid_baseline_releases
)


# Print a heading for evaluation dataset validation
print("\n=== EVALUATION DATASET VALIDATION ===")

# Print the total number of unseen evaluation Change Requests
print("Evaluation CRs:", len(evaluation_df))

# Count evaluation CRs that do not have any ground-truth relevant artifacts
evaluation_without_ground_truth = (
    evaluation_df["Ground_Truth_Count"] == 0
).sum()

# Print the number of evaluation CRs without ground-truth artifacts
print(
    "Evaluation CRs without ground truth:",
    evaluation_without_ground_truth
)

# Print the minimum number of ground-truth artifacts assigned to an evaluation CR
print(
    "Minimum ground-truth count:",
    evaluation_df["Ground_Truth_Count"].min()
)

# Print the maximum number of ground-truth artifacts assigned to an evaluation CR
print(
    "Maximum ground-truth count:",
    evaluation_df["Ground_Truth_Count"].max()
)

# Print a final completion message after all validation checks have run
print("\n=== DATA QUALITY VALIDATION COMPLETE ===")

=== MAIN DATASET VALIDATION ===
Total records: 5000
Unique IDs: 5000
Duplicate IDs: 0
Expected 5,000 records: True

Artifact type distribution:
Type
ALM Test Case        1984
Change Request        764
ALM Specification     733
Task                  652
Problem Report        483
ALM Requirement       314
Release                50
ALM Input              18
ALM Test Suite          2
Name: count, dtype: int64

=== CONTENT VALIDATION ===
ALM artifacts missing Text: 0
CR/PR/Task/Release missing Summary: 0

=== DUPLICATE CONTENT VALIDATION ===
Duplicate non-empty Text values: 2712
Duplicate non-empty Summary values: 1569

=== SPAWNS VALIDATION ===
Total Spawns references: 4752
Resolved Spawns references: 4752
Unresolved Spawns references: 0
Spawns resolution: 100.00%

=== COVERS VALIDATION ===
Total Covers references: 1899
Resolved Covers references: 1899
Unresolved Covers references: 0
Covers resolution: 100.00%

=== BASELINE VALIDATION ===
Total baseline records: 3871
Artifacts with baselines: 1939
Releases represented: 50
Invalid baseline Artifact_ID references: 0
Invalid baseline Release_ID references: 0

=== EVALUATION DATASET VALIDATION ===
Evaluation CRs: 100
Evaluation CRs without ground truth: 0
Minimum ground-truth count: 111
Maximum ground-truth count: 167

=== DATA QUALITY VALIDATION COMPLETE ===